<?php

return [
    'role' => [
        'admin' => 'admin',
    ],
    'subjectType' => [
        'basic' => 1
    ],
    'limit' => [
        'studentInClass' => 20,
    ],
    'guard' => [
        'admin' => 'admin',
        'web' => 'web',
    ],
    'roles' => [
        'superAdmin' => [
            'name' => 'super-admin',
            'guard' => 'admin',
        ],
        'admin' => [
            'name' => 'admin',
            'guard' => 'admin',
            'permissions' => [
                "listSubject" => "list-subject",
                "showSubject" => "show-subject",
                "updateSubject" => "update-subject",
                "createSubject" => "create-subject",
                "deleteSubject" => "delete-subject",
                "listMark" => "list-mark",
                "showMark" => "show-mark",
                "updateMark" => "update-mark",
                "createMark" => "create-mark",
                "deleteMark" => "delete-mark",
                "listStudent" => "list-student",
                "showStudent" => "show-student",
                "updateStudent" => "update-student",
                "createStudent" => "create-student",
                "deleteStudent" => "delete-student",
                "listAdmin" => "list-admin",
                "showAdmin" => "show-admin",
                "updateAdmin" => "update-admin",
                "createAdmin" => "create-admin",
                "deleteAdmin" => "delete-admin",
                "listSchedule" => "list-schedule",
                "showSchedule" => "show-schedule",
                "updateSchedule" => "update-schedule",
                "createSchedule" => "create-schedule",
                "deleteSchedule" => "delete-schedule",
            ],
        ],
        'teacher' => [
            'name' => 'teacher',
            'guard' => 'admin',
            'permissions' => [
                "listSubject" => "list-subject",
                "showSubject" => "show-subject",
                "updateSubject" => "update-subject",
                "createSubject" => "create-subject",
                "deleteSubject" => "delete-subject",
                "listMark" => "list-mark",
                "showMark" => "show-mark",
                "updateMark" => "update-mark",
                "createMark" => "create-mark",
                "deleteMark" => "delete-mark",
                "listStudent" => "list-student",
                "showStudent" => "show-student",
                "updateStudent" => "update-student",
                "createStudent" => "create-student",
                "deleteStudent" => "delete-student",
                "listAdmin" => "list-admin",
                "showAdmin" => "show-admin",
                "updateAdmin" => "update-admin",
                "createAdmin" => "create-admin",
                "deleteAdmin" => "delete-admin",
                "listSchedule" => "list-schedule",
                "showSchedule" => "show-schedule",
                "updateSchedule" => "update-schedule",
                "createSchedule" => "create-schedule",
                "deleteSchedule" => "delete-schedule",
            ],
        ],
        'student' => [
            'name' => 'student',
            'guard' => 'student',
            'permissions' => [
                "listSubject" => "list-subject",
                "showSubject" => "show-subject",
                "updateSubject" => "update-subject",
                "createSubject" => "create-subject",
                "deleteSubject" => "delete-subject",
                "listMark" => "list-mark",
                "showMark" => "show-mark",
                "updateMark" => "update-mark",
                "createMark" => "create-mark",
                "deleteMark" => "delete-mark",
                "listStudent" => "list-student",
                "showStudent" => "show-student",
                "updateStudent" => "update-student",
                "createStudent" => "create-student",
                "deleteStudent" => "delete-student",
                "listAdmin" => "list-admin",
                "showAdmin" => "show-admin",
                "updateAdmin" => "update-admin",
                "createAdmin" => "create-admin",
                "deleteAdmin" => "delete-admin",
                "listSchedule" => "list-schedule",
                "showSchedule" => "show-schedule",
                "updateSchedule" => "update-schedule",
                "createSchedule" => "create-schedule",
                "deleteSchedule" => "delete-schedule",
            ],
        ],
    ]
];
